# Permalinks
#
# Plugins
gems: [jekyll-paginate]  # https://github.com/poole/lanyon/issues/124

# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true # https://github.com/poole/lanyon/issues/124

# Setup
title:               mcmordie.net
tagline:             'Learning to Program'
description:         'Documenting my journey as I <s>struggle</s> persevere to learn how to program.'
url:                 http://mcmordie.net
baseurl:             ''
paginate:            5
paginate_path: "page:num" # https://github.com/poole/lanyon/issues/124

# About/contact
author:
  name:              Chris McMordie
  url:               https://twitter.com/cmcmordie
  email:             cmcmordie@charter.net
  github:            github.com/mcmo

# Custom vars
# version:             1.0.0
